pyms:
  services:
    metrics: true
    tracer:
      enabled: false
  config:
    debug: true
    app_name: alertmanager-actions

alertmanager_actions:
  - name: TestActions
    labels:
      alertname: TestActions
    command: |
      echo $ACTION
      echo $ALERTNAME
